name: Run Tests #action名称
on: 
  push:
    branches:
      - 'main'
jobs:
  build_job:
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps:
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v2    #这里使用了github官方提供的action,checkout项目到虚拟机上
      
      - name: Check
        run: pwd ; ls